spring:
  application:
    name: springboot-app-security
  security:
    user:
      name: test
      password: test
server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
